apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: allow-basic
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'runtime/default,docker/default'
    apparmor.security.beta.kubernetes.io/allowedProfileNames: 'runtime/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'runtime/default'
    apparmor.security.beta.kubernetes.io/defaultProfileName:  'runtime/default'
spec:
  privileged: false
  # Prevent container user from becoming root
  allowPrivilegeEscalation: false
  # Don't allow any capabilities by default (see also https://www.vultr.com/docs/working-with-linux-capabilities)
  requiredDropCapabilities:
    - ALL
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: MustRunAsNonRoot
  supplementalGroups:
    rule: MayRunAs
    ranges:
      - min: 1
        max: 65535
  fsGroup:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 65535
  seLinux:
    rule: RunAsAny
  volumes:
    - downwardAPI
    - configMap
    - secret
    - emptyDir
    - projected
    - persistentVolumeClaim
