apiVersion: constraints.gatekeeper.sh/v1beta1
kind: DenyAutoMountDefaultServiceAccountToken
metadata:
  name: deny-auto-mount-default-service-account-token
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment"]
      - apiGroups: [""]
        kinds: ["Pod"]
